
on:
  push:
     branches: [master]
  pull_request:
     branches: [master]

name: R-CMD-check-fedora
     
jobs:
  R-CMD-check-fedora:
    
    runs-on: ${{ matrix.config.os }}

    name: fedora-latest (${{ matrix.config.compiler }}-${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,   r: 'devel', compiler: 'gcc', image: 'rhub/fedora-gcc-devel:latest'}
          - {os: ubuntu-latest,   r: 'devel', compiler: 'clang', image: 'rhub/fedora-clang-devel:latest'}
          
    container:
      image: ${{ matrix.config.image }}
      
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      RGL_USE_NULL: true
      DISPLAY: 99.0
      
    steps:
    - uses: actions/checkout@v3
    
    - name: setup-r
      run: |
        sudo ln -s /opt/R-devel/bin/R /usr/local/bin/R
        sudo ln -s /opt/R-devel/bin/Rscript /usr/local/bin/Rscript
      shell: bash
      
    - name: installing rgl support on Fedora
      run: |
        sudo dnf install -y mesa-libGL-devel mesa-libGLU-devel libpng-devel
      shell: bash
    
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        extra-packages: any::rcmdcheck
        needs: check

    - uses: r-lib/actions/check-r-package@v2
      with:
        upload-snapshots: true
          